In [1]:
import pandas as pd
import plotly.express as px

- UTF-8: Universal, multilingual.
- latin1: Western European languages.
- latin2: Central European languages.
- latin7: Baltic languages.
- UTF-16: Asian, multilingual.
- ASCII: Basic English text.

In [2]:
df = pd.read_csv('23-24Union_Budget.csv', encoding='latin1')
df

,Ministry,Ministry/Demand,Budget Estimates2023-2024-Revenue,Budget Estimates2023-2024-Capital,Budget Estimates2023-2024-Total
0,Ministry of Agriculture and Farmers Welfare,Total,124982.96,52.83,125035.79
1,Ministry of Agriculture and Farmers Welfare,1. Department of Agriculture and Farmers Welfare,115489.37,42.42,115531.79
2,Ministry of Agriculture and Farmers Welfare,2. Department of Agricultural Research and Edu...,9493.59,10.41,9504.00
3,Department of Atomic Energy,Total,9096.99,15981.50,25078.49
4,Department of Atomic Energy,3. Atomic Energy,9096.99,15981.50,25078.49
...,...,...,...,...,...
154,Ministry of Women and Child Development,Total,25443.67,5.08,25448.75
155,Ministry of Women and Child Development,101. Ministry of Women and Child Development,25443.67,5.08,25448.75
156,Ministry of Youth Affairs and Sports,Total,3389.56,7.76,3397.32
157,Ministry of Youth Affairs and Sports,102. Ministry of Youth Affairs and Sports,3389.56,7.76,3397.32
158,Grand Total,Grand Total,3502136.44,1000961.01,4503097.45

In [3]:
# Standardize column names
df.columns = ['Ministry', 'Demand', 'Budget_2023_Revenue', 'Budget_2023_Capital', 'Budget_2023_Total']

# Remove "Grand Total" row
df = df[df['Ministry'] != 'Grand Total']

In [4]:

# Handle missing values
df.fillna(0, inplace=True)

C:\Users\gaura\AppData\Local\Temp\ipykernel_16776\1750672196.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.fillna(0, inplace=True)

In [5]:

# Convert budget columns to numeric
numeric_cols = ['Budget_2023_Revenue', 'Budget_2023_Capital', 'Budget_2023_Total']
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

C:\Users\gaura\AppData\Local\Temp\ipykernel_16776\3514818639.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

In [6]:

# Add derived metrics
total_budget = df['Budget_2023_Total'].sum()
df['Percentage_of_Total'] = (df['Budget_2023_Total'] / total_budget) * 100
df['Budget_Category'] = pd.cut(df['Budget_2023_Total'], 
                               bins=[0, 5000, 20000, df['Budget_2023_Total'].max()], 
                               labels=['Low', 'Medium', 'High'])

C:\Users\gaura\AppData\Local\Temp\ipykernel_16776\2295334120.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Percentage_of_Total'] = (df['Budget_2023_Total'] / total_budget) * 100
C:\Users\gaura\AppData\Local\Temp\ipykernel_16776\2295334120.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Budget_Category'] = pd.cut(df['Budget_2023_Total'],

In [7]:
df

,Ministry,Demand,Budget_2023_Revenue,Budget_2023_Capital,Budget_2023_Total,Percentage_of_Total,Budget_Category
0,Ministry of Agriculture and Farmers Welfare,Total,124982.96,52.83,125035.79,1.388331,High
1,Ministry of Agriculture and Farmers Welfare,1. Department of Agriculture and Farmers Welfare,115489.37,42.42,115531.79,1.282804,High
2,Ministry of Agriculture and Farmers Welfare,2. Department of Agricultural Research and Edu...,9493.59,10.41,9504.00,0.105527,Medium
3,Department of Atomic Energy,Total,9096.99,15981.50,25078.49,0.278458,High
4,Department of Atomic Energy,3. Atomic Energy,9096.99,15981.50,25078.49,0.278458,High
...,...,...,...,...,...,...,...
153,Ministry of Tribal Affairs,100. Ministry of Tribal Affairs,12414.95,46.93,12461.88,0.138370,Medium
154,Ministry of Women and Child Development,Total,25443.67,5.08,25448.75,0.282569,High
155,Ministry of Women and Child Development,101. Ministry of Women and Child Development,25443.67,5.08,25448.75,0.282569,High
156,Ministry of Youth Affairs and Sports,Total,3389.56,7.76,3397.32,0.037722,Low
157,Ministry of Youth Affairs and Sports,102. Ministry of Youth Affairs and Sports,3389.56,7.76,3397.32,0.037722,Low

In [12]:
#remove any rows with missing values
df.dropna(inplace=True)

In [13]:
# Save cleaned data
df.to_csv('cleaned_budget_data.csv', index=False)

In [14]:
df=pd.read_csv('cleaned_budget_data.csv')

In [15]:
df.dtypes

Ministry                object
Demand                  object
Budget_2023_Revenue    float64
Budget_2023_Capital    float64
Budget_2023_Total      float64
Percentage_of_Total    float64
Budget_Category         object
dtype: object

In [16]:
df.head()

,Ministry,Demand,Budget_2023_Revenue,Budget_2023_Capital,Budget_2023_Total,Percentage_of_Total,Budget_Category
0,Ministry of Agriculture and Farmers Welfare,Total,124982.96,52.83,125035.79,1.388331,High
1,Ministry of Agriculture and Farmers Welfare,1. Department of Agriculture and Farmers Welfare,115489.37,42.42,115531.79,1.282804,High
2,Ministry of Agriculture and Farmers Welfare,2. Department of Agricultural Research and Edu...,9493.59,10.41,9504.00,0.105527,Medium
3,Department of Atomic Energy,Total,9096.99,15981.50,25078.49,0.278458,High
4,Department of Atomic Energy,3. Atomic Energy,9096.99,15981.50,25078.49,0.278458,High